apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ingress.yaml

# Add environment-specific labels
commonLabels:
  environment: dev

# Patch the argocd-server service to use ClusterIP instead of LoadBalancer
# Add tolerations for Fargate nodes
patchesStrategicMerge:
- service-patch.yaml
- tolerations-patch.yaml
