name: PR Checks

on:
  pull_request:
    branches:
      - main
    paths:
      - 'lib/**'
      - 'bin/**'
      - '.github/workflows/**'
      - 'Dockerfile.*'

env:
  NODE_VERSION: '18'

jobs:
  validate:
    name: Validate Infrastructure
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: TypeScript check
        run: npm run build
        
      - name: Install AWS CDK
        run: npm install -g aws-cdk
        
      - name: CDK Synth
        run: cdk synth
        
      - name: CDK Diff
        run: cdk diff || true
        
  docker-build:
    name: Validate Docker Builds
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build frontend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.frontend
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Build backend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.backend
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
